language: python
python: 3.7
dist: xenial
sudo: required

install:
  - pip install -r requirements.txt

script:
  #- python -m pytest --cov-config .coveragerc --cov=delphin_6_automation pytest/
  - python -m pytest pytest/

services:
  - mongodb

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

after_success:
  - coverage report
  - coveralls