version: '3.7'

services:

  simulation:
    image: hpc_simulator:latest
    volumes:
      - ribuild_volume:/app/data
    deploy:
      replicas: 1
    secrets:
      - ssh_key
      - db_ait
      - hpc_ocni

  sampling:
    image: sampler:latest
    secrets:
      - db_ait

volumes:
  ribuild_volume:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: ocni@transfer.gbar.dtu.dk:/zhome/ad/9/77586/ribuild

secrets:
  ssh_key:
    file: /home/ocni/.ssh/id_rsa
  db_ait:
    file: /home/ocni/.ssh/db_ait.json
  hpc_ocni:
    file: /home/ocni/.ssh/hpc_ait.json