version: '3.7'

services:

  simulation_ocni_2d1d:
    image: ocni/hpc_simulator:latest
    volumes:
      - ocni_volume:/app/data
    deploy:
      replicas: 1
    secrets:
      - ssh_key
      - source: db_simon
        target: db_ait
      - source: hpc_ocni
        target: hpc_access

  simulation_thper_2d1d:
    image: ocni/hpc_simulator:latest
    volumes:
      - thper_volume:/app/data
    deploy:
      replicas: 1
    secrets:
      - ssh_key
      - source: db_simon
        target: db_ait
      - source: hpc_thper
        target: hpc_access

  sampling_2d1d:
    image: ocni/hpc_sampler:latest
    secrets:
      - source: db_simon
        target: db_ait

  logger:
    image: iamatypeofwalrus/logspout-loggly
    environment:
      - LOGGLY_TOKEN=2cb6ff7e-c529-446e-b7a7-193ea64de90f
      - LOGGLY_TAG=DOCKER
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


volumes:
  ocni_volume:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: ocni@transfer.gbar.dtu.dk:/zhome/ad/9/77586/ribuild
      IdentityFile: /home/ocni/.ssh/id_rsa
  thper_volume:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: thper@transfer.gbar.dtu.dk:/zhome/dc/d/63949/ribuild
      IdentityFile: /home/ocni/.ssh/id_rsa

secrets:
  ssh_key:
    file: /home/ocni/.ssh/id_rsa
  db_ait:
    file: /home/ocni/.ssh/db_ait.json
  db_simon:
    file: /home/ocni/.ssh/db_simon.json
  hpc_ocni:
    file: /home/ocni/.ssh/hpc_ocni.json
  hpc_thper:
    file: /home/ocni/.ssh/hpc_thper.json
