version: '3.7'

services:

  simulation:
    image: hpc_simulator:latest
    volumes:
      - ribuild_volume:/app/data
    deploy:
      replicas: 2
    secrets:
      - ssh_key
      - db_ait
      - hpc_ocni
    links:
      - logger
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.{{.Name}}


  logger:
    image: fluent/fluentd:latest
    volumes:
      - /home/ocni/delphin_6_automation/docker/fluent:/fluentd/etc
      - /home/ocni/delphin_6_automation/docker/fluent/logs:/fluentd/log
    environment:
      - FLUENTD_CONF=fluent.conf
    ports:
      - "24224:24224/udp"
      - "24224:24224"


  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


volumes:
  ribuild_volume:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: ocni@transfer.gbar.dtu.dk:/zhome/ad/9/77586/ribuild

secrets:
  ssh_key:
    file: /home/ocni/.ssh/id_rsa
  db_ait:
    file: /home/ocni/.ssh/db_ait.json
  hpc_ocni:
    file: /home/ocni/.ssh/hpc_ocni.json
