version: '0'

services:

  simulation:
    image: hpc_simulator:latest
    volumes:
      - type: volume
        source: ribuild_volume
        target: /app/data

  sampling:
    image: sampler:latest