version: '3'

services:

  simulation:
    image: hpc_simulator:latest
    volumes:
      - ribuild_volume:/app/data
    deploy:
      replicas: 1
    secrets:
      - ssh_key


volumes:
  ribuild_volume:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: ocni@transfer.gbar.dtu.dk:/zhome/ad/9/77586/ribuild

secrets:
  ssh_key:
    file: .ssh/id_rsa