version: '3.7'

services:

  simulation:
    image: hpc_simulator:latest
    volumes:
      - ribuild_volume:/app/data
    deploy:
      replicas: 2
    secrets:
      - ssh_key
      - db_ait
      - hpc_ocni

  logger:
    image: iamatypeofwalrus/logspout-loggly
    environment:
      - LOGGLY_TOKEN=2cb6ff7e-c529-446e-b7a7-193ea64de90f
      - LOGGLY_TAG=DOCKER
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"



  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


volumes:
  ribuild_volume:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: ocni@transfer.gbar.dtu.dk:/zhome/ad/9/77586/ribuild

secrets:
  ssh_key:
    file: /home/ocni/.ssh/id_rsa
  db_ait:
    file: /home/ocni/.ssh/db_ait.json
  hpc_ocni:
    file: /home/ocni/.ssh/hpc_ocni.json
