version: '3'

services:

  simulation:
    image: hpc_simulator:latest
    volumes:
      - ribuild_volume:/app/data
    deploy:
      replicas: 5


volumes:
  ribuild_volume: -d vieux/sshfs -o sshcmd=ocni@transfer.gbar.dtu.dk:/zhome/ad/9/77586