version: '3.7'

services:

  sampling:
    image: ocni/hpc_sampler:latest
    secrets:
      - db_ait

  #checker:
  #  image: ocni/hpc_checker:latest
  #  secrets:
  #    - ssh_key
  #    - hpc_ocni

  check_sim:
    image: ocni/hpc_check_sim:latest
    secrets:
      - db_ait

secrets:
  ssh_key:
    file: /home/ocni/.ssh/id_rsa
  db_ait:
    file: /home/ocni/.ssh/db_ait.json
  #hpc_ocni:
  #  file: /home/ocni/.ssh/hpc_ocni.json
